import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`antialiased flex flex-col items-center justify-center min-h-screen`}>
      <h1>Profile Page</h1>
      {children}
    </main>
  );
}
